name: Ruby on Rails CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: asnica_recipe_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    container:
      image: ruby:3.2.2
      env:
        RAILS_ENV: test
        RAILS_DATABASE_HOST: postgres # this is needed
        RAILS_DATABASE_USER: pguser
        RAILS_DATABASE_PASSWORD: password
    

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
  
      - name: Database create and migrate
        run: |
          cp config/database.yml.ci config/database.yml
          bin/rails db:create
          bin/rails db:migrate
  
      - name: Run RSpec
        run: bundle exec rspec
  
      - name: Run RuboCop
        run: bundle exec rubocop